### ISSUE TITLE
Allow --ignore-dir to be more flexible

### ISSUE THREAD

**Issue by hoelzro** [beyondgrep/ack2#42]
The `--ignore-dir` option currently only supports direct matches (ex. `--ignore-dir=is,extlib`; `--ignore-dir=extlib` is just shorthand for that).  In the future, it'd be nice to allow more complex match types.

**Comment by mMontu** [comment]
I think this feature can be very useful, but it seems it was removed (under ack 2.14):

```
$ ack --follow -i --ignore-dir=match:abc 'pattern'
Non-is filters are not yet supported for --ignore-dir at /usr/bin/ack line 155.
        main::_compile_file_filter(HASH(0xf96bc0), ARRAY(0xe3a498)) called at /usr/bin/ack line 946
        main::main() called at /usr/bin/ack line 73
```

And it seems the code from the commits above were removed (as I couldn't find references to `ignore_dirs_re` or the check for 'match' in the _compile_descend_filter subroutine).

@hoelzro do you know if this feature was removed or replaced by an equivalent?

**Comment by petdance** [comment]
It's working for me.  What version of ack are you running?  Can you paste `ack --version`?

**Comment by petdance** [comment]
2.14 was released Wed Sep  3 22:48:00 CDT 2014, but @hoelzro said above her merged it on Nov 3, 2014, after the release of 2.14.  I suggest you move up to 2.16 (or really, to 2.18 which is the latest).

**Comment by mMontu** [comment]
Oh, it is pretty old indeed. I'll try a newer version.
Thanks for the lightning quick response

**Comment by mMontu** [comment]
Indeed, it is working in the latest version.
I thought this option would solve my problem, because I misread the text below:

> I mentioned that the patch is missing a few things; here they are:
> 
>     --ignore-dir=match:... checks the expression against the full path to the directory, rather than the directory name itself (eg. foo/bar/baz rather than just baz)

I was looking for a way to make ack ignore some some specific directories in different projects, i.e., some way to workaround the limitation of the directory specified to --ignore-dir be a simple directory name, to make it possible to ignore a given directory name in a project while searching a directory with the same name in another project.

It turned out that project specific ackrcs are good solution for this.
Thanks!
