### ISSUE TITLE
Better Bash Completion

### ISSUE THREAD

**Issue by starcraftman** [beyondgrep/ack2#554]
There are some problems with current bash completion this project provides. May apply to zsh as well, though I don't currently have a replacement for that one.

1) Not distributed as shown by #486, even if the generator were packaged ~~it requires the Template.pm module & App::Ack be installed~~(edit: forgot about the make target for this). For people just fetching the standalone bit of a nuisance having to get whole repo + gen make etc...

1) The generated bash completion hard codes the strings for long/short opts. You need to regenerate on every change.

1) Some completions aren't handled well, like `ack --type=` & `ack --type`. In the former, no options appear, the latter misses the no equivalents. Some other things like color completion not there.

I noticed all this at this point as I was redoing some of my own bash completion scripts. I believe I've made a bash completer that is a good improvement. You can see it in my own dotfiles [here](https://github.com/starcraftman/dot/blob/master/files/bash_completions/_ack). It uses ack itself to parse the opts. This means that completer should complete any version of ack, past or future.

I didn't make a PR because I think this has to be discussed re your mailing list & also something similar would have to be done for zsh I suppose. As a consequence of this change, you could simply point people to a link for the completer rather than building it That's tangential though, I'd mainly just like the default bash completion better for users.

**Comment by starcraftman** [comment]
Regarding zsh completion, I could point out this excellent project which I use. https://github.com/zsh-users/zsh-completions

It maintains completions for _ack (among others, like _ag). If we went with my proposal re downloading, it would be trivial to apply patches to them on any major changes and simply download the raw _ack zsh completion.

**Comment by hoelzro** [comment]
Hi @starcraftman, thanks for the input!  To address each of your points...

* The generated files *should* be distributed in the tarballs, but the generating scripts are fairly new.
* The bash script hard codes options so that `ack --help` doesn't need to be run every time the user hits tab; it looks like the zsh script still does this to fill in user-defined types, so that could probably stand to change.
* `ack --type` completion probably doesn't work as well in bash because I mainly did work for the zsh version; any fixes via a PR would be appreciated!

Why don't you open up a post on the mailing list to discuss this; I think you've pointed out some valid problems, though, so opening up a PR to address them would be spectacular.  We're in kind of a code freeze at the moment, but your changes would probably go out in 2.18!

**Comment by petdance** [comment]
Personally, I would rather point people at the zsh-completions project than to distribute the file as part of the ack distro.

**Comment by starcraftman** [comment]
@hoelzro To clarify on point 2, I employ caching to avoid this on **every** tab. The parsing happens only once per terminal session, which seems an acceptable trade of. See [here](https://github.com/starcraftman/dot/blob/master/files/bash_completions/_ack#L9-L28). Parsing user types is something I could add, though I never really used that.

**Comment by petdance** [comment]
There will probably be no more releases of ack 2.  If this is still a relevant idea, please submit it to the ack3 repo at https://github.com/beyondgrep/ack3.
